-- type_response_values.sql — SUPERSEDED; retained for reference only.
--
-- As of the inline-typing refactor, typed value columns (response_value_as_concept_id,
-- response_value_as_date, response_value_as_number) are computed directly in each
-- unpivot_*.sql INSERT using CASE/REGEXP_CONTAINS — no separate UPDATE step needed.
-- Running this file is now a no-op (all rows already have typed values populated).
--
-- ROUTING LOGIC (documented here for reference; lives in generate_unpivot_sql.py):
--   9-digit integer     → response_value_as_concept_id  (coded single/multi-select answer)
--   ISO date YYYY-MM-DD → response_value_as_date        (Special Functions date questions)
--   numeric (non-9-digit, non-date) → response_value_as_number (Num/Year/count question)
--   anything else       → stays only in response_value_as_string (free text / unrecognized)
--
-- See docs/value_typing.md for a full account of limitations and edge cases.
